/****************************************************************************/
/*                      FD helpers, SymPy generated                         */
/*                                                                          */
/*  Generated by fd_emit.py — DO NOT EDIT BY HAND.                          */
/*  Source: ~/grace_notebooks/Z4c/fd_emit.py                                */
/*                                                                          */
/*  Every operator is templated on the FD truncation order; supported       */
/*  orders are {2, 4, 6}.  Symmetry-equivariant grouping is baked into      */
/*  the generated C99 expression (antisym pair, sym pair, 4-corner mixed,   */
/*  upwind = centred + KO correction), so partner-equivariance under        */
/*  coordinate-reflection symmetries holds at IEEE FP precision by          */
/*  construction.                                                           */
/****************************************************************************/
#ifndef GRACE_FD_SUBEXPR_HH
#define GRACE_FD_SUBEXPR_HH

#include <Kokkos_Core.hpp>

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_x(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered 1st derivative along x.
	// Antisymmetric-pair grouping (u(+a) - u(-a)) so partial sums
	// commute exactly under mirror sign-flip in IEEE FP.
	if constexpr ( Order == 2 ) {
		*du = (1.0/2.0)*invh*(
	      +       (u(i+1,j,k) - u(i-1,j,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*invh*(
	          +8.0 * (u(i+1,j,k) - u(i-1,j,k))
	      -       (u(i+2,j,k) - u(i-2,j,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/60.0)*invh*(
	         +45.0 * (u(i+1,j,k) - u(i-1,j,k))
	          -9.0 * (u(i+2,j,k) - u(i-2,j,k))
	      +       (u(i+3,j,k) - u(i-3,j,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_x: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_x_l1(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Biased 1st derivative along x, shift -1.  Boundary stencil.
	// Canonical form; its mirror partner fd_der_{axis}_r1 is emitted
	// with the negated-and-mirrored expression for bit-exact symmetry.
	if constexpr ( Order == 2 ) {
		*du = (1.0/2.0)*invh*(+u(i-2,j,k) -4*u(i-1,j,k) +3*u(i,j,k));
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*invh*(-u(i-3,j,k) +6*u(i-2,j,k) -18*u(i-1,j,k) +10*u(i,j,k) +3*u(i+1,j,k));
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/60.0)*invh*(+u(i-4,j,k) -8*u(i-3,j,k) +30*u(i-2,j,k) -80*u(i-1,j,k) +35*u(i,j,k) +24*u(i+1,j,k) -2*u(i+2,j,k));
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_x_l1: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_x_r1(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Biased 1st derivative along x, shift +1.  Bit-mirror
	// partner of fd_der_x_l1 under i -> -i:
	//   R1(i, ...) := -( L1(i, ...) with all offsets mirrored ).
	// The partial-sum tree matches L1 cell-for-cell, so the
	// negation is IEEE-exact and partner-equivariance holds at
	// the FP floor.  Strict superset of canonical emission.
	if constexpr ( Order == 2 ) {
		*du = -(1.0/2.0)*invh*(+u(i+2,j,k) -4*u(i+1,j,k) +3*u(i,j,k));
	}
	else if constexpr ( Order == 4 ) {
		*du = -(1.0/12.0)*invh*(-u(i+3,j,k) +6*u(i+2,j,k) -18*u(i+1,j,k) +10*u(i,j,k) +3*u(i-1,j,k));
	}
	else if constexpr ( Order == 6 ) {
		*du = -(1.0/60.0)*invh*(+u(i+4,j,k) -8*u(i+3,j,k) +30*u(i+2,j,k) -80*u(i+1,j,k) +35*u(i,j,k) +24*u(i-1,j,k) -2*u(i-2,j,k));
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_x_r1: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_y(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered 1st derivative along y.
	// Antisymmetric-pair grouping (u(+a) - u(-a)) so partial sums
	// commute exactly under mirror sign-flip in IEEE FP.
	if constexpr ( Order == 2 ) {
		*du = (1.0/2.0)*invh*(
	      +       (u(i,j+1,k) - u(i,j-1,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*invh*(
	          +8.0 * (u(i,j+1,k) - u(i,j-1,k))
	      -       (u(i,j+2,k) - u(i,j-2,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/60.0)*invh*(
	         +45.0 * (u(i,j+1,k) - u(i,j-1,k))
	          -9.0 * (u(i,j+2,k) - u(i,j-2,k))
	      +       (u(i,j+3,k) - u(i,j-3,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_y: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_y_l1(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Biased 1st derivative along y, shift -1.  Boundary stencil.
	// Canonical form; its mirror partner fd_der_{axis}_r1 is emitted
	// with the negated-and-mirrored expression for bit-exact symmetry.
	if constexpr ( Order == 2 ) {
		*du = (1.0/2.0)*invh*(+u(i,j-2,k) -4*u(i,j-1,k) +3*u(i,j,k));
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*invh*(-u(i,j-3,k) +6*u(i,j-2,k) -18*u(i,j-1,k) +10*u(i,j,k) +3*u(i,j+1,k));
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/60.0)*invh*(+u(i,j-4,k) -8*u(i,j-3,k) +30*u(i,j-2,k) -80*u(i,j-1,k) +35*u(i,j,k) +24*u(i,j+1,k) -2*u(i,j+2,k));
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_y_l1: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_y_r1(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Biased 1st derivative along y, shift +1.  Bit-mirror
	// partner of fd_der_y_l1 under i -> -i:
	//   R1(i, ...) := -( L1(i, ...) with all offsets mirrored ).
	// The partial-sum tree matches L1 cell-for-cell, so the
	// negation is IEEE-exact and partner-equivariance holds at
	// the FP floor.  Strict superset of canonical emission.
	if constexpr ( Order == 2 ) {
		*du = -(1.0/2.0)*invh*(+u(i,j+2,k) -4*u(i,j+1,k) +3*u(i,j,k));
	}
	else if constexpr ( Order == 4 ) {
		*du = -(1.0/12.0)*invh*(-u(i,j+3,k) +6*u(i,j+2,k) -18*u(i,j+1,k) +10*u(i,j,k) +3*u(i,j-1,k));
	}
	else if constexpr ( Order == 6 ) {
		*du = -(1.0/60.0)*invh*(+u(i,j+4,k) -8*u(i,j+3,k) +30*u(i,j+2,k) -80*u(i,j+1,k) +35*u(i,j,k) +24*u(i,j-1,k) -2*u(i,j-2,k));
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_y_r1: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_z(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered 1st derivative along z.
	// Antisymmetric-pair grouping (u(+a) - u(-a)) so partial sums
	// commute exactly under mirror sign-flip in IEEE FP.
	if constexpr ( Order == 2 ) {
		*du = (1.0/2.0)*invh*(
	      +       (u(i,j,k+1) - u(i,j,k-1))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*invh*(
	          +8.0 * (u(i,j,k+1) - u(i,j,k-1))
	      -       (u(i,j,k+2) - u(i,j,k-2))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/60.0)*invh*(
	         +45.0 * (u(i,j,k+1) - u(i,j,k-1))
	          -9.0 * (u(i,j,k+2) - u(i,j,k-2))
	      +       (u(i,j,k+3) - u(i,j,k-3))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_z: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_z_l1(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Biased 1st derivative along z, shift -1.  Boundary stencil.
	// Canonical form; its mirror partner fd_der_{axis}_r1 is emitted
	// with the negated-and-mirrored expression for bit-exact symmetry.
	if constexpr ( Order == 2 ) {
		*du = (1.0/2.0)*invh*(+u(i,j,k-2) -4*u(i,j,k-1) +3*u(i,j,k));
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*invh*(-u(i,j,k-3) +6*u(i,j,k-2) -18*u(i,j,k-1) +10*u(i,j,k) +3*u(i,j,k+1));
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/60.0)*invh*(+u(i,j,k-4) -8*u(i,j,k-3) +30*u(i,j,k-2) -80*u(i,j,k-1) +35*u(i,j,k) +24*u(i,j,k+1) -2*u(i,j,k+2));
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_z_l1: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_z_r1(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Biased 1st derivative along z, shift +1.  Bit-mirror
	// partner of fd_der_z_l1 under i -> -i:
	//   R1(i, ...) := -( L1(i, ...) with all offsets mirrored ).
	// The partial-sum tree matches L1 cell-for-cell, so the
	// negation is IEEE-exact and partner-equivariance holds at
	// the FP floor.  Strict superset of canonical emission.
	if constexpr ( Order == 2 ) {
		*du = -(1.0/2.0)*invh*(+u(i,j,k+2) -4*u(i,j,k+1) +3*u(i,j,k));
	}
	else if constexpr ( Order == 4 ) {
		*du = -(1.0/12.0)*invh*(-u(i,j,k+3) +6*u(i,j,k+2) -18*u(i,j,k+1) +10*u(i,j,k) +3*u(i,j,k-1));
	}
	else if constexpr ( Order == 6 ) {
		*du = -(1.0/60.0)*invh*(+u(i,j,k+4) -8*u(i,j,k+3) +30*u(i,j,k+2) -80*u(i,j,k+1) +35*u(i,j,k) +24*u(i,j,k-1) -2*u(i,j,k-2));
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_z_r1: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_xx(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered 2nd derivative along x.
	// Symmetric-pair grouping (u(+a) + u(-a)) for IEEE FP
	// partner-equivariance.
	if constexpr ( Order == 2 ) {
		*du = (1.0/1.0)*((invh)*(invh))*(
	          -2.0 * u(i,j,k)
	      +        (u(i+1,j,k) + u(i-1,j,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*((invh)*(invh))*(
	         -30.0 * u(i,j,k)
	         +16.0 * (u(i+1,j,k) + u(i-1,j,k))
	      -        (u(i+2,j,k) + u(i-2,j,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/180.0)*((invh)*(invh))*(
	        -490.0 * u(i,j,k)
	        +270.0 * (u(i+1,j,k) + u(i-1,j,k))
	         -27.0 * (u(i+2,j,k) + u(i-2,j,k))
	          +2.0 * (u(i+3,j,k) + u(i-3,j,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_xx: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_yy(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered 2nd derivative along y.
	// Symmetric-pair grouping (u(+a) + u(-a)) for IEEE FP
	// partner-equivariance.
	if constexpr ( Order == 2 ) {
		*du = (1.0/1.0)*((invh)*(invh))*(
	          -2.0 * u(i,j,k)
	      +        (u(i,j+1,k) + u(i,j-1,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*((invh)*(invh))*(
	         -30.0 * u(i,j,k)
	         +16.0 * (u(i,j+1,k) + u(i,j-1,k))
	      -        (u(i,j+2,k) + u(i,j-2,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/180.0)*((invh)*(invh))*(
	        -490.0 * u(i,j,k)
	        +270.0 * (u(i,j+1,k) + u(i,j-1,k))
	         -27.0 * (u(i,j+2,k) + u(i,j-2,k))
	          +2.0 * (u(i,j+3,k) + u(i,j-3,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_yy: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_zz(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered 2nd derivative along z.
	// Symmetric-pair grouping (u(+a) + u(-a)) for IEEE FP
	// partner-equivariance.
	if constexpr ( Order == 2 ) {
		*du = (1.0/1.0)*((invh)*(invh))*(
	          -2.0 * u(i,j,k)
	      +        (u(i,j,k+1) + u(i,j,k-1))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/12.0)*((invh)*(invh))*(
	         -30.0 * u(i,j,k)
	         +16.0 * (u(i,j,k+1) + u(i,j,k-1))
	      -        (u(i,j,k+2) + u(i,j,k-2))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/180.0)*((invh)*(invh))*(
	        -490.0 * u(i,j,k)
	        +270.0 * (u(i,j,k+1) + u(i,j,k-1))
	         -27.0 * (u(i,j,k+2) + u(i,j,k-2))
	          +2.0 * (u(i,j,k+3) + u(i,j,k-3))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_zz: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_xy(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered mixed 2nd derivative d2/dxdy.
	// 4-corner antisym-pair grouping X(a,b) = (u(+a,+b) + u(-a,-b))
	// - (u(+a,-b) + u(-a,+b)), bit-equivariant under any transform
	// that flips x or y.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*((invh)*(invh))*(
	      + ((u(i+1,j+1,k) + u(i-1,j-1,k)) - (u(i+1,j-1,k) + u(i-1,j+1,k)))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/144.0)*((invh)*(invh))*(
	      +64.0 * ((u(i+1,j+1,k) + u(i-1,j-1,k)) - (u(i+1,j-1,k) + u(i-1,j+1,k)))
	      -8.0 * ((u(i+1,j+2,k) + u(i-1,j-2,k)) - (u(i+1,j-2,k) + u(i-1,j+2,k)))
	      -8.0 * ((u(i+2,j+1,k) + u(i-2,j-1,k)) - (u(i+2,j-1,k) + u(i-2,j+1,k)))
	      + ((u(i+2,j+2,k) + u(i-2,j-2,k)) - (u(i+2,j-2,k) + u(i-2,j+2,k)))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/3600.0)*((invh)*(invh))*(
	      +2025.0 * ((u(i+1,j+1,k) + u(i-1,j-1,k)) - (u(i+1,j-1,k) + u(i-1,j+1,k)))
	      -405.0 * ((u(i+1,j+2,k) + u(i-1,j-2,k)) - (u(i+1,j-2,k) + u(i-1,j+2,k)))
	      +45.0 * ((u(i+1,j+3,k) + u(i-1,j-3,k)) - (u(i+1,j-3,k) + u(i-1,j+3,k)))
	      -405.0 * ((u(i+2,j+1,k) + u(i-2,j-1,k)) - (u(i+2,j-1,k) + u(i-2,j+1,k)))
	      +81.0 * ((u(i+2,j+2,k) + u(i-2,j-2,k)) - (u(i+2,j-2,k) + u(i-2,j+2,k)))
	      -9.0 * ((u(i+2,j+3,k) + u(i-2,j-3,k)) - (u(i+2,j-3,k) + u(i-2,j+3,k)))
	      +45.0 * ((u(i+3,j+1,k) + u(i-3,j-1,k)) - (u(i+3,j-1,k) + u(i-3,j+1,k)))
	      -9.0 * ((u(i+3,j+2,k) + u(i-3,j-2,k)) - (u(i+3,j-2,k) + u(i-3,j+2,k)))
	      + ((u(i+3,j+3,k) + u(i-3,j-3,k)) - (u(i+3,j-3,k) + u(i-3,j+3,k)))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_xy: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_xz(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered mixed 2nd derivative d2/dxdz.
	// 4-corner antisym-pair grouping X(a,b) = (u(+a,+b) + u(-a,-b))
	// - (u(+a,-b) + u(-a,+b)), bit-equivariant under any transform
	// that flips x or z.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*((invh)*(invh))*(
	      + ((u(i+1,j,k+1) + u(i-1,j,k-1)) - (u(i+1,j,k-1) + u(i-1,j,k+1)))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/144.0)*((invh)*(invh))*(
	      +64.0 * ((u(i+1,j,k+1) + u(i-1,j,k-1)) - (u(i+1,j,k-1) + u(i-1,j,k+1)))
	      -8.0 * ((u(i+1,j,k+2) + u(i-1,j,k-2)) - (u(i+1,j,k-2) + u(i-1,j,k+2)))
	      -8.0 * ((u(i+2,j,k+1) + u(i-2,j,k-1)) - (u(i+2,j,k-1) + u(i-2,j,k+1)))
	      + ((u(i+2,j,k+2) + u(i-2,j,k-2)) - (u(i+2,j,k-2) + u(i-2,j,k+2)))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/3600.0)*((invh)*(invh))*(
	      +2025.0 * ((u(i+1,j,k+1) + u(i-1,j,k-1)) - (u(i+1,j,k-1) + u(i-1,j,k+1)))
	      -405.0 * ((u(i+1,j,k+2) + u(i-1,j,k-2)) - (u(i+1,j,k-2) + u(i-1,j,k+2)))
	      +45.0 * ((u(i+1,j,k+3) + u(i-1,j,k-3)) - (u(i+1,j,k-3) + u(i-1,j,k+3)))
	      -405.0 * ((u(i+2,j,k+1) + u(i-2,j,k-1)) - (u(i+2,j,k-1) + u(i-2,j,k+1)))
	      +81.0 * ((u(i+2,j,k+2) + u(i-2,j,k-2)) - (u(i+2,j,k-2) + u(i-2,j,k+2)))
	      -9.0 * ((u(i+2,j,k+3) + u(i-2,j,k-3)) - (u(i+2,j,k-3) + u(i-2,j,k+3)))
	      +45.0 * ((u(i+3,j,k+1) + u(i-3,j,k-1)) - (u(i+3,j,k-1) + u(i-3,j,k+1)))
	      -9.0 * ((u(i+3,j,k+2) + u(i-3,j,k-2)) - (u(i+3,j,k-2) + u(i-3,j,k+2)))
	      + ((u(i+3,j,k+3) + u(i-3,j,k-3)) - (u(i+3,j,k-3) + u(i-3,j,k+3)))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_xz: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_yz(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Centered mixed 2nd derivative d2/dydz.
	// 4-corner antisym-pair grouping X(a,b) = (u(+a,+b) + u(-a,-b))
	// - (u(+a,-b) + u(-a,+b)), bit-equivariant under any transform
	// that flips y or z.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*((invh)*(invh))*(
	      + ((u(i,j+1,k+1) + u(i,j-1,k-1)) - (u(i,j+1,k-1) + u(i,j-1,k+1)))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/144.0)*((invh)*(invh))*(
	      +64.0 * ((u(i,j+1,k+1) + u(i,j-1,k-1)) - (u(i,j+1,k-1) + u(i,j-1,k+1)))
	      -8.0 * ((u(i,j+1,k+2) + u(i,j-1,k-2)) - (u(i,j+1,k-2) + u(i,j-1,k+2)))
	      -8.0 * ((u(i,j+2,k+1) + u(i,j-2,k-1)) - (u(i,j+2,k-1) + u(i,j-2,k+1)))
	      + ((u(i,j+2,k+2) + u(i,j-2,k-2)) - (u(i,j+2,k-2) + u(i,j-2,k+2)))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/3600.0)*((invh)*(invh))*(
	      +2025.0 * ((u(i,j+1,k+1) + u(i,j-1,k-1)) - (u(i,j+1,k-1) + u(i,j-1,k+1)))
	      -405.0 * ((u(i,j+1,k+2) + u(i,j-1,k-2)) - (u(i,j+1,k-2) + u(i,j-1,k+2)))
	      +45.0 * ((u(i,j+1,k+3) + u(i,j-1,k-3)) - (u(i,j+1,k-3) + u(i,j-1,k+3)))
	      -405.0 * ((u(i,j+2,k+1) + u(i,j-2,k-1)) - (u(i,j+2,k-1) + u(i,j-2,k+1)))
	      +81.0 * ((u(i,j+2,k+2) + u(i,j-2,k-2)) - (u(i,j+2,k-2) + u(i,j-2,k+2)))
	      -9.0 * ((u(i,j+2,k+3) + u(i,j-2,k-3)) - (u(i,j+2,k-3) + u(i,j-2,k+3)))
	      +45.0 * ((u(i,j+3,k+1) + u(i,j-3,k-1)) - (u(i,j+3,k-1) + u(i,j-3,k+1)))
	      -9.0 * ((u(i,j+3,k+2) + u(i,j-3,k-2)) - (u(i,j+3,k-2) + u(i,j-3,k+2)))
	      + ((u(i,j+3,k+3) + u(i,j-3,k-3)) - (u(i,j+3,k-3) + u(i,j-3,k+3)))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_yz: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_x_upw_pos(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Upwind 1st derivative along x, v > 0.
	// Decomposed as (antisym centered piece) + (sym KO-correction
	// piece) so the centered piece flips sign IEEE-exactly under
	// mirror while the correction is preserved IEEE-exactly.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*invh*(
	            +4.0 * (u(i+1,j,k) - u(i-1,j,k))
	      -         (u(i+2,j,k) - u(i-2,j,k))
	            -6.0 * u(i,j,k)
	            +4.0 * (u(i+1,j,k) + u(i-1,j,k))
	      -         (u(i+2,j,k) + u(i-2,j,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/24.0)*invh*(
	           +21.0 * (u(i+1,j,k) - u(i-1,j,k))
	            -6.0 * (u(i+2,j,k) - u(i-2,j,k))
	      +         (u(i+3,j,k) - u(i-3,j,k))
	           -20.0 * u(i,j,k)
	           +15.0 * (u(i+1,j,k) + u(i-1,j,k))
	            -6.0 * (u(i+2,j,k) + u(i-2,j,k))
	      +         (u(i+3,j,k) + u(i-3,j,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/120.0)*invh*(
	          +104.0 * (u(i+1,j,k) - u(i-1,j,k))
	           -32.0 * (u(i+2,j,k) - u(i-2,j,k))
	            +8.0 * (u(i+3,j,k) - u(i-3,j,k))
	      -         (u(i+4,j,k) - u(i-4,j,k))
	           -70.0 * u(i,j,k)
	           +56.0 * (u(i+1,j,k) + u(i-1,j,k))
	           -28.0 * (u(i+2,j,k) + u(i-2,j,k))
	            +8.0 * (u(i+3,j,k) + u(i-3,j,k))
	      -         (u(i+4,j,k) + u(i-4,j,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_x_upw_pos: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_x_upw_neg(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Upwind 1st derivative along x, v < 0.
	// Decomposed as (antisym centered piece) + (sym KO-correction
	// piece) so the centered piece flips sign IEEE-exactly under
	// mirror while the correction is preserved IEEE-exactly.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*invh*(
	            +4.0 * (u(i+1,j,k) - u(i-1,j,k))
	      -         (u(i+2,j,k) - u(i-2,j,k))
	            +6.0 * u(i,j,k)
	            -4.0 * (u(i+1,j,k) + u(i-1,j,k))
	      +         (u(i+2,j,k) + u(i-2,j,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/24.0)*invh*(
	           +21.0 * (u(i+1,j,k) - u(i-1,j,k))
	            -6.0 * (u(i+2,j,k) - u(i-2,j,k))
	      +         (u(i+3,j,k) - u(i-3,j,k))
	           +20.0 * u(i,j,k)
	           -15.0 * (u(i+1,j,k) + u(i-1,j,k))
	            +6.0 * (u(i+2,j,k) + u(i-2,j,k))
	      -         (u(i+3,j,k) + u(i-3,j,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/120.0)*invh*(
	          +104.0 * (u(i+1,j,k) - u(i-1,j,k))
	           -32.0 * (u(i+2,j,k) - u(i-2,j,k))
	            +8.0 * (u(i+3,j,k) - u(i-3,j,k))
	      -         (u(i+4,j,k) - u(i-4,j,k))
	           +70.0 * u(i,j,k)
	           -56.0 * (u(i+1,j,k) + u(i-1,j,k))
	           +28.0 * (u(i+2,j,k) + u(i-2,j,k))
	            -8.0 * (u(i+3,j,k) + u(i-3,j,k))
	      +         (u(i+4,j,k) + u(i-4,j,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_x_upw_neg: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_y_upw_pos(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Upwind 1st derivative along y, v > 0.
	// Decomposed as (antisym centered piece) + (sym KO-correction
	// piece) so the centered piece flips sign IEEE-exactly under
	// mirror while the correction is preserved IEEE-exactly.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*invh*(
	            +4.0 * (u(i,j+1,k) - u(i,j-1,k))
	      -         (u(i,j+2,k) - u(i,j-2,k))
	            -6.0 * u(i,j,k)
	            +4.0 * (u(i,j+1,k) + u(i,j-1,k))
	      -         (u(i,j+2,k) + u(i,j-2,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/24.0)*invh*(
	           +21.0 * (u(i,j+1,k) - u(i,j-1,k))
	            -6.0 * (u(i,j+2,k) - u(i,j-2,k))
	      +         (u(i,j+3,k) - u(i,j-3,k))
	           -20.0 * u(i,j,k)
	           +15.0 * (u(i,j+1,k) + u(i,j-1,k))
	            -6.0 * (u(i,j+2,k) + u(i,j-2,k))
	      +         (u(i,j+3,k) + u(i,j-3,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/120.0)*invh*(
	          +104.0 * (u(i,j+1,k) - u(i,j-1,k))
	           -32.0 * (u(i,j+2,k) - u(i,j-2,k))
	            +8.0 * (u(i,j+3,k) - u(i,j-3,k))
	      -         (u(i,j+4,k) - u(i,j-4,k))
	           -70.0 * u(i,j,k)
	           +56.0 * (u(i,j+1,k) + u(i,j-1,k))
	           -28.0 * (u(i,j+2,k) + u(i,j-2,k))
	            +8.0 * (u(i,j+3,k) + u(i,j-3,k))
	      -         (u(i,j+4,k) + u(i,j-4,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_y_upw_pos: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_y_upw_neg(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Upwind 1st derivative along y, v < 0.
	// Decomposed as (antisym centered piece) + (sym KO-correction
	// piece) so the centered piece flips sign IEEE-exactly under
	// mirror while the correction is preserved IEEE-exactly.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*invh*(
	            +4.0 * (u(i,j+1,k) - u(i,j-1,k))
	      -         (u(i,j+2,k) - u(i,j-2,k))
	            +6.0 * u(i,j,k)
	            -4.0 * (u(i,j+1,k) + u(i,j-1,k))
	      +         (u(i,j+2,k) + u(i,j-2,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/24.0)*invh*(
	           +21.0 * (u(i,j+1,k) - u(i,j-1,k))
	            -6.0 * (u(i,j+2,k) - u(i,j-2,k))
	      +         (u(i,j+3,k) - u(i,j-3,k))
	           +20.0 * u(i,j,k)
	           -15.0 * (u(i,j+1,k) + u(i,j-1,k))
	            +6.0 * (u(i,j+2,k) + u(i,j-2,k))
	      -         (u(i,j+3,k) + u(i,j-3,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/120.0)*invh*(
	          +104.0 * (u(i,j+1,k) - u(i,j-1,k))
	           -32.0 * (u(i,j+2,k) - u(i,j-2,k))
	            +8.0 * (u(i,j+3,k) - u(i,j-3,k))
	      -         (u(i,j+4,k) - u(i,j-4,k))
	           +70.0 * u(i,j,k)
	           -56.0 * (u(i,j+1,k) + u(i,j-1,k))
	           +28.0 * (u(i,j+2,k) + u(i,j-2,k))
	            -8.0 * (u(i,j+3,k) + u(i,j-3,k))
	      +         (u(i,j+4,k) + u(i,j-4,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_y_upw_neg: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_z_upw_pos(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Upwind 1st derivative along z, v > 0.
	// Decomposed as (antisym centered piece) + (sym KO-correction
	// piece) so the centered piece flips sign IEEE-exactly under
	// mirror while the correction is preserved IEEE-exactly.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*invh*(
	            +4.0 * (u(i,j,k+1) - u(i,j,k-1))
	      -         (u(i,j,k+2) - u(i,j,k-2))
	            -6.0 * u(i,j,k)
	            +4.0 * (u(i,j,k+1) + u(i,j,k-1))
	      -         (u(i,j,k+2) + u(i,j,k-2))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/24.0)*invh*(
	           +21.0 * (u(i,j,k+1) - u(i,j,k-1))
	            -6.0 * (u(i,j,k+2) - u(i,j,k-2))
	      +         (u(i,j,k+3) - u(i,j,k-3))
	           -20.0 * u(i,j,k)
	           +15.0 * (u(i,j,k+1) + u(i,j,k-1))
	            -6.0 * (u(i,j,k+2) + u(i,j,k-2))
	      +         (u(i,j,k+3) + u(i,j,k-3))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/120.0)*invh*(
	          +104.0 * (u(i,j,k+1) - u(i,j,k-1))
	           -32.0 * (u(i,j,k+2) - u(i,j,k-2))
	            +8.0 * (u(i,j,k+3) - u(i,j,k-3))
	      -         (u(i,j,k+4) - u(i,j,k-4))
	           -70.0 * u(i,j,k)
	           +56.0 * (u(i,j,k+1) + u(i,j,k-1))
	           -28.0 * (u(i,j,k+2) + u(i,j,k-2))
	            +8.0 * (u(i,j,k+3) + u(i,j,k-3))
	      -         (u(i,j,k+4) + u(i,j,k-4))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_z_upw_pos: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_der_z_upw_neg(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Upwind 1st derivative along z, v < 0.
	// Decomposed as (antisym centered piece) + (sym KO-correction
	// piece) so the centered piece flips sign IEEE-exactly under
	// mirror while the correction is preserved IEEE-exactly.
	if constexpr ( Order == 2 ) {
		*du = (1.0/4.0)*invh*(
	            +4.0 * (u(i,j,k+1) - u(i,j,k-1))
	      -         (u(i,j,k+2) - u(i,j,k-2))
	            +6.0 * u(i,j,k)
	            -4.0 * (u(i,j,k+1) + u(i,j,k-1))
	      +         (u(i,j,k+2) + u(i,j,k-2))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/24.0)*invh*(
	           +21.0 * (u(i,j,k+1) - u(i,j,k-1))
	            -6.0 * (u(i,j,k+2) - u(i,j,k-2))
	      +         (u(i,j,k+3) - u(i,j,k-3))
	           +20.0 * u(i,j,k)
	           -15.0 * (u(i,j,k+1) + u(i,j,k-1))
	            +6.0 * (u(i,j,k+2) + u(i,j,k-2))
	      -         (u(i,j,k+3) + u(i,j,k-3))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/120.0)*invh*(
	          +104.0 * (u(i,j,k+1) - u(i,j,k-1))
	           -32.0 * (u(i,j,k+2) - u(i,j,k-2))
	            +8.0 * (u(i,j,k+3) - u(i,j,k-3))
	      -         (u(i,j,k+4) - u(i,j,k-4))
	           +70.0 * u(i,j,k)
	           -56.0 * (u(i,j,k+1) + u(i,j,k-1))
	           +28.0 * (u(i,j,k+2) + u(i,j,k-2))
	            -8.0 * (u(i,j,k+3) + u(i,j,k-3))
	      +         (u(i,j,k+4) + u(i,j,k-4))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_der_z_upw_neg: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_diss_x(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Kreiss-Oliger dissipation along x.
	// KO order = FD order + 1; stencil width = FD order + 2.
	// Symmetric-pair grouping for partner-equivariance.
	if constexpr ( Order == 2 ) {
		*du = (1.0/1.0)*invh*(
	          +6.0 * u(i,j,k)
	          -4.0 * (u(i+1,j,k) + u(i-1,j,k))
	      +        (u(i+2,j,k) + u(i-2,j,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/1.0)*invh*(
	         -20.0 * u(i,j,k)
	         +15.0 * (u(i+1,j,k) + u(i-1,j,k))
	          -6.0 * (u(i+2,j,k) + u(i-2,j,k))
	      +        (u(i+3,j,k) + u(i-3,j,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/1.0)*invh*(
	         +70.0 * u(i,j,k)
	         -56.0 * (u(i+1,j,k) + u(i-1,j,k))
	         +28.0 * (u(i+2,j,k) + u(i-2,j,k))
	          -8.0 * (u(i+3,j,k) + u(i-3,j,k))
	      +        (u(i+4,j,k) + u(i-4,j,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_diss_x: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_diss_y(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Kreiss-Oliger dissipation along y.
	// KO order = FD order + 1; stencil width = FD order + 2.
	// Symmetric-pair grouping for partner-equivariance.
	if constexpr ( Order == 2 ) {
		*du = (1.0/1.0)*invh*(
	          +6.0 * u(i,j,k)
	          -4.0 * (u(i,j+1,k) + u(i,j-1,k))
	      +        (u(i,j+2,k) + u(i,j-2,k))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/1.0)*invh*(
	         -20.0 * u(i,j,k)
	         +15.0 * (u(i,j+1,k) + u(i,j-1,k))
	          -6.0 * (u(i,j+2,k) + u(i,j-2,k))
	      +        (u(i,j+3,k) + u(i,j-3,k))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/1.0)*invh*(
	         +70.0 * u(i,j,k)
	         -56.0 * (u(i,j+1,k) + u(i,j-1,k))
	         +28.0 * (u(i,j+2,k) + u(i,j-2,k))
	          -8.0 * (u(i,j+3,k) + u(i,j-3,k))
	      +        (u(i,j+4,k) + u(i,j-4,k))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_diss_y: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fd_diss_z(
	view_t u,
	int i,
	int j,
	int k,
	double invh,
	double * __restrict__ du
)
{
	// Kreiss-Oliger dissipation along z.
	// KO order = FD order + 1; stencil width = FD order + 2.
	// Symmetric-pair grouping for partner-equivariance.
	if constexpr ( Order == 2 ) {
		*du = (1.0/1.0)*invh*(
	          +6.0 * u(i,j,k)
	          -4.0 * (u(i,j,k+1) + u(i,j,k-1))
	      +        (u(i,j,k+2) + u(i,j,k-2))
	);
	}
	else if constexpr ( Order == 4 ) {
		*du = (1.0/1.0)*invh*(
	         -20.0 * u(i,j,k)
	         +15.0 * (u(i,j,k+1) + u(i,j,k-1))
	          -6.0 * (u(i,j,k+2) + u(i,j,k-2))
	      +        (u(i,j,k+3) + u(i,j,k-3))
	);
	}
	else if constexpr ( Order == 6 ) {
		*du = (1.0/1.0)*invh*(
	         +70.0 * u(i,j,k)
	         -56.0 * (u(i,j,k+1) + u(i,j,k-1))
	         +28.0 * (u(i,j,k+2) + u(i,j,k-2))
	          -8.0 * (u(i,j,k+3) + u(i,j,k-3))
	      +        (u(i,j,k+4) + u(i,j,k-4))
	);
	}
	else {
		static_assert( Order==2 || Order==4 || Order==6,
			"fd_diss_z: unsupported FD order" );
	}
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_deriv_scalar(view_t state, int i, int j, int k, int iv, int q, double d[3], double invh)
{
	using namespace Kokkos;
	auto u = subview(state,ALL(),ALL(),ALL(),iv,q);
	fd_der_x<Order>(u,i,j,k,invh,&(d[0]));
	fd_der_y<Order>(u,i,j,k,invh,&(d[1]));
	fd_der_z<Order>(u,i,j,k,invh,&(d[2]));
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_deriv_vector(view_t state, int i, int j, int k, int iv, int q, double d[9], double invh)
{
	using namespace Kokkos;
	auto ux = subview(state,ALL(),ALL(),ALL(),iv,q)  ;
	auto uy = subview(state,ALL(),ALL(),ALL(),iv+1,q);
	auto uz = subview(state,ALL(),ALL(),ALL(),iv+2,q);
	fd_der_x<Order>(ux,i,j,k,invh,&(d[0]));
	fd_der_x<Order>(uy,i,j,k,invh,&(d[1]));
	fd_der_x<Order>(uz,i,j,k,invh,&(d[2]));
	fd_der_y<Order>(ux,i,j,k,invh,&(d[3]));
	fd_der_y<Order>(uy,i,j,k,invh,&(d[4]));
	fd_der_y<Order>(uz,i,j,k,invh,&(d[5]));
	fd_der_z<Order>(ux,i,j,k,invh,&(d[6]));
	fd_der_z<Order>(uy,i,j,k,invh,&(d[7]));
	fd_der_z<Order>(uz,i,j,k,invh,&(d[8]));
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_deriv_tensor(view_t state, int i, int j, int k, int iv, int q, double d[18], double invh)
{
	using namespace Kokkos;
	auto uxx = subview(state,ALL(),ALL(),ALL(),iv,q)  ;
	auto uxy = subview(state,ALL(),ALL(),ALL(),iv+1,q);
	auto uxz = subview(state,ALL(),ALL(),ALL(),iv+2,q);
	auto uyy = subview(state,ALL(),ALL(),ALL(),iv+3,q);
	auto uyz = subview(state,ALL(),ALL(),ALL(),iv+4,q);
	auto uzz = subview(state,ALL(),ALL(),ALL(),iv+5,q);
	fd_der_x<Order>(uxx,i,j,k,invh,&(d[0]));
	fd_der_x<Order>(uxy,i,j,k,invh,&(d[1]));
	fd_der_x<Order>(uxz,i,j,k,invh,&(d[2]));
	fd_der_x<Order>(uyy,i,j,k,invh,&(d[3]));
	fd_der_x<Order>(uyz,i,j,k,invh,&(d[4]));
	fd_der_x<Order>(uzz,i,j,k,invh,&(d[5]));
	fd_der_y<Order>(uxx,i,j,k,invh,&(d[6]));
	fd_der_y<Order>(uxy,i,j,k,invh,&(d[7]));
	fd_der_y<Order>(uxz,i,j,k,invh,&(d[8]));
	fd_der_y<Order>(uyy,i,j,k,invh,&(d[9]));
	fd_der_y<Order>(uyz,i,j,k,invh,&(d[10]));
	fd_der_y<Order>(uzz,i,j,k,invh,&(d[11]));
	fd_der_z<Order>(uxx,i,j,k,invh,&(d[12]));
	fd_der_z<Order>(uxy,i,j,k,invh,&(d[13]));
	fd_der_z<Order>(uxz,i,j,k,invh,&(d[14]));
	fd_der_z<Order>(uyy,i,j,k,invh,&(d[15]));
	fd_der_z<Order>(uyz,i,j,k,invh,&(d[16]));
	fd_der_z<Order>(uzz,i,j,k,invh,&(d[17]));
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_second_deriv_scalar(view_t state, int i, int j, int k, int iv, int q, double d[6], double invh)
{
	using namespace Kokkos;
	auto u = subview(state,ALL(),ALL(),ALL(),iv,q);
	fd_der_xx<Order>(u,i,j,k,invh,&(d[0]));
	fd_der_xy<Order>(u,i,j,k,invh,&(d[1]));
	fd_der_xz<Order>(u,i,j,k,invh,&(d[2]));
	fd_der_yy<Order>(u,i,j,k,invh,&(d[3]));
	fd_der_yz<Order>(u,i,j,k,invh,&(d[4]));
	fd_der_zz<Order>(u,i,j,k,invh,&(d[5]));
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_second_deriv_vector(view_t state, int i, int j, int k, int iv, int q, double d[18], double invh)
{
	using namespace Kokkos;
	auto ux = subview(state,ALL(),ALL(),ALL(),iv+0,q);
	auto uy = subview(state,ALL(),ALL(),ALL(),iv+1,q);
	auto uz = subview(state,ALL(),ALL(),ALL(),iv+2,q);
	fd_der_xx<Order>(ux,i,j,k,invh,&(d[0]));
	fd_der_xx<Order>(uy,i,j,k,invh,&(d[1]));
	fd_der_xx<Order>(uz,i,j,k,invh,&(d[2]));
	fd_der_xy<Order>(ux,i,j,k,invh,&(d[3]));
	fd_der_xy<Order>(uy,i,j,k,invh,&(d[4]));
	fd_der_xy<Order>(uz,i,j,k,invh,&(d[5]));
	fd_der_xz<Order>(ux,i,j,k,invh,&(d[6]));
	fd_der_xz<Order>(uy,i,j,k,invh,&(d[7]));
	fd_der_xz<Order>(uz,i,j,k,invh,&(d[8]));
	fd_der_yy<Order>(ux,i,j,k,invh,&(d[9]));
	fd_der_yy<Order>(uy,i,j,k,invh,&(d[10]));
	fd_der_yy<Order>(uz,i,j,k,invh,&(d[11]));
	fd_der_yz<Order>(ux,i,j,k,invh,&(d[12]));
	fd_der_yz<Order>(uy,i,j,k,invh,&(d[13]));
	fd_der_yz<Order>(uz,i,j,k,invh,&(d[14]));
	fd_der_zz<Order>(ux,i,j,k,invh,&(d[15]));
	fd_der_zz<Order>(uy,i,j,k,invh,&(d[16]));
	fd_der_zz<Order>(uz,i,j,k,invh,&(d[17]));
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_second_deriv_tensor(view_t state, int i, int j, int k, int iv, int q, double d[36], double invh)
{
	using namespace Kokkos;
	auto uxx = subview(state,ALL(),ALL(),ALL(),iv+0,q);
	auto uxy = subview(state,ALL(),ALL(),ALL(),iv+1,q);
	auto uxz = subview(state,ALL(),ALL(),ALL(),iv+2,q);
	auto uyy = subview(state,ALL(),ALL(),ALL(),iv+3,q);
	auto uyz = subview(state,ALL(),ALL(),ALL(),iv+4,q);
	auto uzz = subview(state,ALL(),ALL(),ALL(),iv+5,q);
	fd_der_xx<Order>(uxx,i,j,k,invh,&(d[0]));
	fd_der_xx<Order>(uxy,i,j,k,invh,&(d[1]));
	fd_der_xx<Order>(uxz,i,j,k,invh,&(d[2]));
	fd_der_xx<Order>(uyy,i,j,k,invh,&(d[3]));
	fd_der_xx<Order>(uyz,i,j,k,invh,&(d[4]));
	fd_der_xx<Order>(uzz,i,j,k,invh,&(d[5]));
	fd_der_xy<Order>(uxx,i,j,k,invh,&(d[6]));
	fd_der_xy<Order>(uxy,i,j,k,invh,&(d[7]));
	fd_der_xy<Order>(uxz,i,j,k,invh,&(d[8]));
	fd_der_xy<Order>(uyy,i,j,k,invh,&(d[9]));
	fd_der_xy<Order>(uyz,i,j,k,invh,&(d[10]));
	fd_der_xy<Order>(uzz,i,j,k,invh,&(d[11]));
	fd_der_xz<Order>(uxx,i,j,k,invh,&(d[12]));
	fd_der_xz<Order>(uxy,i,j,k,invh,&(d[13]));
	fd_der_xz<Order>(uxz,i,j,k,invh,&(d[14]));
	fd_der_xz<Order>(uyy,i,j,k,invh,&(d[15]));
	fd_der_xz<Order>(uyz,i,j,k,invh,&(d[16]));
	fd_der_xz<Order>(uzz,i,j,k,invh,&(d[17]));
	fd_der_yy<Order>(uxx,i,j,k,invh,&(d[18]));
	fd_der_yy<Order>(uxy,i,j,k,invh,&(d[19]));
	fd_der_yy<Order>(uxz,i,j,k,invh,&(d[20]));
	fd_der_yy<Order>(uyy,i,j,k,invh,&(d[21]));
	fd_der_yy<Order>(uyz,i,j,k,invh,&(d[22]));
	fd_der_yy<Order>(uzz,i,j,k,invh,&(d[23]));
	fd_der_yz<Order>(uxx,i,j,k,invh,&(d[24]));
	fd_der_yz<Order>(uxy,i,j,k,invh,&(d[25]));
	fd_der_yz<Order>(uxz,i,j,k,invh,&(d[26]));
	fd_der_yz<Order>(uyy,i,j,k,invh,&(d[27]));
	fd_der_yz<Order>(uyz,i,j,k,invh,&(d[28]));
	fd_der_yz<Order>(uzz,i,j,k,invh,&(d[29]));
	fd_der_zz<Order>(uxx,i,j,k,invh,&(d[30]));
	fd_der_zz<Order>(uxy,i,j,k,invh,&(d[31]));
	fd_der_zz<Order>(uxz,i,j,k,invh,&(d[32]));
	fd_der_zz<Order>(uyy,i,j,k,invh,&(d[33]));
	fd_der_zz<Order>(uyz,i,j,k,invh,&(d[34]));
	fd_der_zz<Order>(uzz,i,j,k,invh,&(d[35]));
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_deriv_scalar_upw(view_t state, int i, int j, int k, int iv, int q, double * d, double v[3], double invh)
{
	using namespace Kokkos;
	auto u = subview(state,ALL(),ALL(),ALL(),iv,q);
	(*d) = 0;
	double dl;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(u,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(u,i,j,k,invh,&(dl)); }
	(*d) += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(u,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(u,i,j,k,invh,&(dl)); }
	(*d) += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(u,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(u,i,j,k,invh,&(dl)); }
	(*d) += dl * v[2];
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_deriv_vector_upw(view_t state, int i, int j, int k, int iv, int q, double d[3], double v[3], double invh)
{
	using namespace Kokkos;
	auto ux = subview(state,ALL(),ALL(),ALL(),iv+0,q);
	auto uy = subview(state,ALL(),ALL(),ALL(),iv+1,q);
	auto uz = subview(state,ALL(),ALL(),ALL(),iv+2,q);
	double dl;
	d[0] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(ux,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(ux,i,j,k,invh,&(dl)); }
	d[0] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(ux,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(ux,i,j,k,invh,&(dl)); }
	d[0] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(ux,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(ux,i,j,k,invh,&(dl)); }
	d[0] += dl * v[2];
	d[1] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uy,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uy,i,j,k,invh,&(dl)); }
	d[1] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uy,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uy,i,j,k,invh,&(dl)); }
	d[1] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uy,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uy,i,j,k,invh,&(dl)); }
	d[1] += dl * v[2];
	d[2] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uz,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uz,i,j,k,invh,&(dl)); }
	d[2] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uz,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uz,i,j,k,invh,&(dl)); }
	d[2] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uz,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uz,i,j,k,invh,&(dl)); }
	d[2] += dl * v[2];
}

template< int Order, typename view_t >
static void KOKKOS_INLINE_FUNCTION
fill_deriv_tensor_upw(view_t state, int i, int j, int k, int iv, int q, double d[6], double v[3], double invh)
{
	using namespace Kokkos;
	auto uxx = subview(state,ALL(),ALL(),ALL(),iv+0,q);
	auto uxy = subview(state,ALL(),ALL(),ALL(),iv+1,q);
	auto uxz = subview(state,ALL(),ALL(),ALL(),iv+2,q);
	auto uyy = subview(state,ALL(),ALL(),ALL(),iv+3,q);
	auto uyz = subview(state,ALL(),ALL(),ALL(),iv+4,q);
	auto uzz = subview(state,ALL(),ALL(),ALL(),iv+5,q);
	double dl;
	d[0] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uxx,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uxx,i,j,k,invh,&(dl)); }
	d[0] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uxx,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uxx,i,j,k,invh,&(dl)); }
	d[0] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uxx,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uxx,i,j,k,invh,&(dl)); }
	d[0] += dl * v[2];
	d[1] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uxy,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uxy,i,j,k,invh,&(dl)); }
	d[1] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uxy,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uxy,i,j,k,invh,&(dl)); }
	d[1] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uxy,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uxy,i,j,k,invh,&(dl)); }
	d[1] += dl * v[2];
	d[2] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uxz,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uxz,i,j,k,invh,&(dl)); }
	d[2] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uxz,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uxz,i,j,k,invh,&(dl)); }
	d[2] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uxz,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uxz,i,j,k,invh,&(dl)); }
	d[2] += dl * v[2];
	d[3] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uyy,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uyy,i,j,k,invh,&(dl)); }
	d[3] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uyy,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uyy,i,j,k,invh,&(dl)); }
	d[3] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uyy,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uyy,i,j,k,invh,&(dl)); }
	d[3] += dl * v[2];
	d[4] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uyz,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uyz,i,j,k,invh,&(dl)); }
	d[4] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uyz,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uyz,i,j,k,invh,&(dl)); }
	d[4] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uyz,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uyz,i,j,k,invh,&(dl)); }
	d[4] += dl * v[2];
	d[5] = 0;
	dl = 0.0;
	if (v[0] > 0)      { fd_der_x_upw_pos<Order>(uzz,i,j,k,invh,&(dl)); }
	else if (v[0] < 0) { fd_der_x_upw_neg<Order>(uzz,i,j,k,invh,&(dl)); }
	d[5] += dl * v[0];
	dl = 0.0;
	if (v[1] > 0)      { fd_der_y_upw_pos<Order>(uzz,i,j,k,invh,&(dl)); }
	else if (v[1] < 0) { fd_der_y_upw_neg<Order>(uzz,i,j,k,invh,&(dl)); }
	d[5] += dl * v[1];
	dl = 0.0;
	if (v[2] > 0)      { fd_der_z_upw_pos<Order>(uzz,i,j,k,invh,&(dl)); }
	else if (v[2] < 0) { fd_der_z_upw_neg<Order>(uzz,i,j,k,invh,&(dl)); }
	d[5] += dl * v[2];
}

#endif // GRACE_FD_SUBEXPR_HH
