# CMake generated Testfile for 
# Source directory: /u/cmusolino/grace-pvt/test
# Build directory: /u/cmusolino/grace-pvt/buil-dbg/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(parallel_test "mpirun" "-n" "2" "./parallel_test")
set_tests_properties(parallel_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;105;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(parser_test "./parser_test")
set_tests_properties(parser_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;106;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(sc_wrappers_test "mpirun" "-n" "1" "./sc_wrappers_test" "--grace-parfile" "./configs/basic_config.yaml")
set_tests_properties(sc_wrappers_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;107;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(connectivity_test "mpirun" "-n" "1" "./connectivity_test" "--grace-parfile" "./configs/basic_config.yaml")
set_tests_properties(connectivity_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;109;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(forest_test "mpirun" "-n" "1" "./forest_test" "--grace-parfile" "./configs/basic_config.yaml")
set_tests_properties(forest_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;111;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(varlist_test "mpirun" "-n" "1" "./varlist_test" "--grace-parfile" "./configs/basic_config.yaml")
set_tests_properties(varlist_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;113;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(coordinate_test_nolog "mpirun" "-n" "1" "./coordinate_test" "--grace-parfile" "./configs/basic_config.yaml")
set_tests_properties(coordinate_test_nolog PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;115;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(coordinate_test_log "mpirun" "-n" "1" "./coordinate_test" "--grace-parfile" "./configs/regrid_test_spherical_log.yaml")
set_tests_properties(coordinate_test_log PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;117;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(interpolator_test "./interpolator_test")
set_tests_properties(interpolator_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;119;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(regrid_test_cartesian "mpirun" "-n" "2" "./regrid_test" "--grace-parfile" "./configs/regrid_test_cartesian.yaml")
set_tests_properties(regrid_test_cartesian PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;121;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(regrid_test_nolog "mpirun" "-n" "2" "./regrid_test" "--grace-parfile" "./configs/regrid_test_spherical.yaml")
set_tests_properties(regrid_test_nolog PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;123;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(regrid_test_log "mpirun" "-n" "2" "./regrid_test" "--grace-parfile" "./configs/regrid_test_spherical_log.yaml")
set_tests_properties(regrid_test_log PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;125;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(bc_test_unigrid_cartesian "mpirun" "-n" "2" "./bc_test_unigrid" "--grace-parfile" "./configs/regrid_test_cartesian.yaml")
set_tests_properties(bc_test_unigrid_cartesian PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;127;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(bc_test_unigrid_spherical "mpirun" "-n" "2" "./bc_test_unigrid" "--grace-parfile" "./configs/regrid_test_spherical.yaml")
set_tests_properties(bc_test_unigrid_spherical PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;129;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(bc_test_cartesian "mpirun" "-n" "2" "./bc_test" "--grace-parfile" "./configs/regrid_test_cartesian.yaml")
set_tests_properties(bc_test_cartesian PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;131;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(bc_test_spherical "mpirun" "-n" "2" "./bc_test" "--grace-parfile" "./configs/regrid_test_spherical.yaml")
set_tests_properties(bc_test_spherical PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;133;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(scalar_reductions_test "mpirun" "-n" "1" "./scalar_reductions_test" "--grace-parfile" "./configs/scalar_reductions_test.yaml")
set_tests_properties(scalar_reductions_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;135;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(pwpoly_test "mpirun" "-n" "1" "./eos_test" "--grace-parfile" "./configs/pwpoly_test_config.yaml")
set_tests_properties(pwpoly_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;137;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(metric_test "mpirun" "-n" "1" "./metric_test" "--grace-parfile" "./configs/basic_config.yaml")
set_tests_properties(metric_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;139;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(gamma2_c2p_test "mpirun" "-n" "1" "./c2p_test" "--grace-parfile" "./configs/c2p_test_gamma2.yaml")
set_tests_properties(gamma2_c2p_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;141;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
add_test(sly4_pw_c2p_test "mpirun" "-n" "1" "./c2p_test" "--grace-parfile" "./configs/c2p_test_sly4_pw.yaml")
set_tests_properties(sly4_pw_c2p_test PROPERTIES  _BACKTRACE_TRIPLES "/u/cmusolino/grace-pvt/test/CMakeLists.txt;143;add_test;/u/cmusolino/grace-pvt/test/CMakeLists.txt;0;")
