# magnetized FM torus 
name: "grace"
amr: {
  npoints_block_x: 16,
  npoints_block_y: 16,
  npoints_block_z: 16,
  xmin: -128.0,
  xmax:  128.0,
  ymin: -128.0,
  ymax:  128.0,
  zmin: -128.0,
  zmax:  128.0,
  n_ghostzones: 2,
  initial_refinement_level: 0,
  refinement_criterion_CTORE: 1e-1,
  refinement_criterion_CTODE: 1e-5,
  refinement_criterion_var  : "rho",
  refinement_criterion_var_is_aux: true,
  refinement_criterion: "simple_threshold",
  # refinement_criterion_CTORE: 0.5,
  # refinement_criterion_CTODE: 0.75,
  # refinement_criterion_var  : "alp",
  # refinement_criterion_var_is_aux: false,
  # refinement_criterion: "simple_threshold",
  max_refinement_level: 5,
  postinitial_regrid_depth: 3,
  regrid_every: -1,
  #regrid_at_postinitial: true # FIX ME: regrid at postinitial does not work 
                               # manifests either at the control-flow points:
                               # C2P problems: 0-setting of conservs at some points in the grid?
                               # timestep 
  regrid_at_postinitial: true,
  reset_id_after_regrid : true # should we do it?
}
IO: {
  # Bug/Feature: 
  # vel[1]/vel[2] to be specifiable in the future  
  volume_output_cell_variables: ["eps","rho","press","alp", "vel[0]",
                              "B[0]", "phi_glm", "divB", "g[0][0]"],
  volume_output_base_directory: "output_volume",
  volume_output_every: 1,
  plane_surface_output_cell_variables: [],
  plane_surface_output_every: -1,
  sphere_surface_output_every: -1,
  info_output_every: 10,

  info_output_max_reductions: ["press", "rho", "vel[0]", "B[0]", "B[1]", "B[2]", "phi_glm","divB"],
  info_output_min_reductions: ["press", "rho", "vel[0]", "B[0]", "B[1]", "B[2]", "phi_glm","divB"],
  scalar_output_every: 10,
  scalar_output_minmax: ["eps","rho","press",
                         "vel[0]", "vel[1]", "vel[2]", 
                         "B[0]", "B[1]", "B[2]",
                         "phi_glm","divB"],
  scalar_output_norm2: [],
  scalar_output_integral: [],
  output_use_hdf5: true, 
  hdf5_compression_level: 6,
  hdf5_chunk_size: 8192
}
system: {
  console_log_level: "debug",
  #console_log_level: "info",
  file_log_level: "trace",
  flush_logs_based_on_severity: true,
  flush_level: "trace"
}
evolution: {
  time_stepper: "rk2",
  # cfl_factor: 0.2,
  cfl_factor: 0.2,
  final_time: 100.0,
  # timestep: 0.0000, # just out of curiosity 
  # timestep_selection_mode: "manual"
}
grmhd: {
  id_type: "FMtorus",
  #lapse_excision : 0.3, # already deep in the horizon btw!
  lapse_excision : 0.3, # already deep in the horizon btw!
  #FMTorus_a_BH:  0.5,
  FMTorus_a_BH:  0.9375,
  FMTorus_M_BH: 1.0,
  FMTorus_rho_min: 1.e-10 ,
  FMTorus_press_min: 1.e-10,
  FMTorus_lapse_min: 0.1 , # disable
  FMTorus_r_rin: 6.0, # inner radius of the disc
  # FMTorus_r_rin: 6.0, # inner radius of the disc
  FMTorus_r_at_max_density: 12.0, # Radius at which disk reaches max density in equatorial plane
  # FMTorus_r_at_max_density: 6.0, # Radius at which disk reaches max density in equatorial plane
  FMTorus_gamma: 1.33333333,
  FMTorus_kappa: 4.249572342033184e-03, #0.017976716690519586, # has to match the one in the EOS setup
  set_B_from_Avec : true,
  Avec_type : "poloidal",
  Avec_prescription : "pressure_prescription",
  Avec_Pcut : 1e-6,
  Avec_Ab : 10.0,
  Avec_n : 2,
  # the above Avec settings give rise to max |B| ~
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",
  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-14,
  eps_maximum: 1.e+05,
  gamma_th: 0.0,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [1.3333333],
    rhos:   [],
    #kappa_0: 100.0
    #kappa_0: 0.017976716690519586 #... ok...
    kappa_0 : 4.249572342033184e-03
  }
}

profiling: {
  do_gpu_profiling: false
}
