name: "grace"
amr: {
  npoints_block_x: 8,
  npoints_block_y: 8,
  npoints_block_z: 8,
  xmin: -1.,
  xmax: 1.,
  ymin: 0.,
  ymax: 1.,
  zmin: 0.,
  zmax: 1.,
  n_ghostzones: 2,
  initial_refinement_level: 2,
  refinement_criterion: "simple_threshold",
  refinement_criterion_CTORE: 2.,
  refinement_criterion_CTODE: 1.,
  refinement_criterion_var: "U",
  max_refinement_level: 7,
  regrid_every: -1,
  regrid_at_postinitial: false
}
IO: {
  volume_output_cell_variables: ["dens", "beta[0]"],
  volume_output_base_directory: "output_volume",
  volume_output_every: -1,
  plane_surface_output_cell_variables: [],
  plane_surface_output_every: 800,
  sphere_surface_output_every: -1,
  info_output_every: 20,
  info_output_max_reductions: ["dens"],
  info_output_min_reductions: ["dens"], 
  scalar_output_every: 50,
  scalar_output_minmax: ["dens"],
  scalar_output_norm2: ["dens"],
  scalar_output_integral: ["dens"],
  output_use_hdf5: true, 
  hdf5_compression_level: 6,
  hdf5_chunk_size: 8192
}
system: {
  console_log_level: "info",
  file_log_level: "trace",
  flush_logs_based_on_severity: true,
  flush_level: "trace"
}