name: "grace"
amr: {
  npoints_block_x: 100,
  npoints_block_y: 100,
  npoints_block_z: 100,
  periodic_x: false,
  periodic_y: false,
  periodic_z: false,
  xmin: -0.5,
  xmax:  0.5,
  ymin: -0.5,
  ymax:  0.5,
  zmin: -0.5,
  zmax:  0.5,
  n_ghostzones: 4,
  initial_refinement_level: 1, #2,
  refinement_criterion: "simple_threshold",
  refinement_criterion_CTORE: 0.5,
  refinement_criterion_CTODE: 0.01,
  prolongation_order: 4 
}
IO: {
  surface_output_base_directory: "output_surface",
  sphere_surface_output_cell_variables: ["Psi4Re","Psi4Im"],
  sphere_surface_integrals_cell_variables: [],
  sphere_surface_multipoles_cell_variables: [],
  sphere_surface_multipoles_max_degree: 4,
  sphere_surface_output_nside : 32, 
  n_output_spheres : 1,
  output_sphere_radius_0 : 0.2,
  output_sphere_type_0 : "healpix"
}
system: {
  console_log_level: "verbose",
  file_log_level: "trace",
  flush_logs_based_on_severity: true,
  flush_level: "trace"
}