# Parameter file for a magnetic rotor
# https://arxiv.org/pdf/2407.20946 (Neuweiler 2024)

name: "grace"
amr: {
  npoints_block_x: 16,
  npoints_block_y: 16,
  npoints_block_z: 16,
  xmin: -0.5,
  xmax:  0.5,
  ymin: -0.5,
  ymax:  0.5,
  zmin: -0.5,
  zmax:  0.5,
  n_ghostzones: 2,
  #initial_refinement_level: 3,
  initial_refinement_level: 4,
  refinement_criterion: "simple_threshold",
  refinement_criterion_CTORE: 2.,
  refinement_criterion_CTODE: 1.,
  refinement_criterion_var: "U",
  max_refinement_level: 7,
  regrid_every: -1,
  regrid_at_postinitial: false,
  periodic_z: true,
}
IO: {
  # Bug/Feature: 
  # vel[1]/vel[2] to be specifiable in the future  
  volume_output_cell_variables: ["eps","rho","press","alp", "vel[0]",
                              "B[0]", "phi_glm"],
  volume_output_base_directory: "output_volume",
  volume_output_every: 5,
  plane_surface_output_cell_variables: [],
  plane_surface_output_every: -1,
  sphere_surface_output_every: -1,
  info_output_every: 10,
  info_output_max_reductions: ["rho", "vel[0]", "B[0]", "B[1]", "B[2]", "phi_glm"],
  info_output_min_reductions: ["rho", "vel[0]", "B[0]", "B[1]", "B[2]", "phi_glm"],
  scalar_output_every: 10,
  scalar_output_minmax: ["eps","rho","press",
                         "vel[0]", "vel[1]", "vel[2]", 
                         "B[0]", "B[1]", "B[2]",
                         "phi_glm"],
  scalar_output_norm2: [],
  scalar_output_integral: [],
  output_use_hdf5: true, 
  hdf5_compression_level: 6,
  hdf5_chunk_size: 8192
}
system: {
  console_log_level: "info",
  file_log_level: "trace",
  flush_logs_based_on_severity: true,
  flush_level: "trace"
}
evolution: {
  time_stepper: "rk2",
  cfl_factor: 0.2,
  final_time: 0.425
}
grmhd: {
  
  id_type: "magnetic_rotor",
  magnetized_rotor_rho_in : 10,
  magnetized_rotor_rho_out : 1.0,
  magnetized_rotor_press : 1.0,
  magnetized_rotor_B0 : 1.0
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",
  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-14,
  eps_maximum: 1.e+05,
  gamma_th: 1.66666,  
 
  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [0.],
    rhos:   [],
    kappa_0: 0
  }
}

profiling: {
  do_gpu_profiling: false
}
