if("${CMAKE_CXX_COMPILER}" MATCHES "hipcc")
    message(STATUS "Compiling with hipcc")
    add_compile_options(-fgpu-rdc)
    add_link_options(-fgpu-rdc --hip-link)
endif()


if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    message("Using Intel compiler.")
    if( CMAKE_CXX_COMPILER_VERSION VERSION_LESS 2021.7.0)
        message(FATAL_ERROR "Intel compiler version must be at least 2021.7.0")
    endif()
    add_compile_options(-diag-disable=10441)
endif()

if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "NVHPC")
    message("Using Nvidia HPC compiler.")
    add_compile_options(--expt-relaxed-constexpr -diag-suppress=20091 -diag-suppress=20012)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lstdc++fs")
endif()