option(THUNDER_ENABLE_BURGERS  "Enable Burgers equation module" OFF) 
option(THUNDER_ENABLE_SCALAR_ADV  "Enable scalar advection equation module" OFF) 
option(THUNDER_ENABLE_GRMHD   "Enable GRMHD equation module"  ON)
if( THUNDER_ENABLE_SCALAR_ADV )
    message(STATUS "Scalar advection module enabled.")
    set(THUNDER_ENABLE_GRMHD OFF)
endif()
if( THUNDER_ENABLE_BURGERS )
    message(STATUS "Burgers module enabled.")
    set(THUNDER_ENABLE_GRMHD OFF)
endif()
if( THUNDER_ENABLE_GRMHD )
    message(STATUS "GRMHD module enabled.")
    set(THUNDER_ENABLE_BURGERS OFF)
endif()

